const DATA={flow:{years:[2022,2023,2024],matriculas:[633688,767713,860791],ingressantes:[425216,489263,509828],concluintes:[64486,84164,106157]},modalities:{2022:{ead:350191,presencial:283497,evasaoEad:23.65,evasaoPres:17.36},2023:{ead:443907,presencial:323806,evasaoEad:24.16,evasaoPres:17.40},2024:{ead:503635,presencial:357156,evasaoEad:26.28,evasaoPres:16.33}},regions:{labels:["Sudeste","Nordeste","Sul","Centro-Oeste","Norte"],values:[448683,147797,142295,80232,41346]},courses:{labels:["Sistemas de Informação","Ciência da Computação","Engenharia de Software","Engenharia de Computação","Gestão de TI","Ciência de Dados","Redes de Computadores","Sistemas para Internet","Interdisciplinares TIC","Defesa Cibernética"],values:[420479,127190,69832,60569,59647,28189,20661,15718,14735,10547]}};
const compact=v=>new Intl.NumberFormat("pt-BR",{notation:"compact",maximumFractionDigits:1}).format(v);const number=v=>new Intl.NumberFormat("pt-BR").format(v);const pct=v=>`${v.toFixed(2).replace(".",",")}%`;
Chart.defaults.font.family="DM Sans";Chart.defaults.color="#78837f";Chart.defaults.plugins.legend.display=false;Chart.defaults.plugins.tooltip.backgroundColor="#10211c";Chart.defaults.plugins.tooltip.padding=12;Chart.defaults.plugins.tooltip.cornerRadius=10;
const grid={color:"rgba(120,131,127,.12)",drawBorder:false};const ticks={callback:compact,font:{size:10}};
new Chart(document.getElementById("flow-chart"),{type:"line",data:{labels:DATA.flow.years,datasets:[{data:DATA.flow.matriculas,borderColor:"#88ad16",backgroundColor:"rgba(202,255,61,.14)",fill:true,tension:.35,borderWidth:3,pointRadius:4,pointBackgroundColor:"#caff3d"},{data:DATA.flow.ingressantes,borderColor:"#48a9ff",tension:.35,borderWidth:3,pointRadius:4},{data:DATA.flow.concluintes,borderColor:"#9a78ff",tension:.35,borderWidth:3,pointRadius:4}]},options:{responsive:true,maintainAspectRatio:false,interaction:{intersect:false,mode:"index"},scales:{x:{grid:{display:false}},y:{beginAtZero:true,grid,ticks}},plugins:{tooltip:{callbacks:{label:c=>`${["Matrículas","Ingressantes","Concluintes"][c.datasetIndex]}: ${number(c.raw)}`}}}}});
let modalityChart=new Chart(document.getElementById("modality-chart"),{type:"doughnut",data:{labels:["EAD","Presencial"],datasets:[{data:[503635,357156],backgroundColor:["#caff3d","#48a9ff"],borderWidth:0,hoverOffset:3}]},options:{responsive:true,maintainAspectRatio:false,cutout:"73%",plugins:{tooltip:{callbacks:{label:c=>`${c.label}: ${number(c.raw)} matrículas`}}}}});
function setYear(year){const d=DATA.modalities[year];const share=d.ead/(d.ead+d.presencial)*100;modalityChart.data.datasets[0].data=[d.ead,d.presencial];modalityChart.update();document.getElementById("ead-share").textContent=`${share.toFixed(1).replace(".",",")}%`;document.getElementById("ead-enrollment").textContent=compact(d.ead);document.getElementById("pres-enrollment").textContent=compact(d.presencial);document.getElementById("ead-evasion").textContent=`${pct(d.evasaoEad)} evasão`;document.getElementById("pres-evasion").textContent=`${pct(d.evasaoPres)} evasão`}
document.querySelectorAll(".year-toggle button").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll(".year-toggle button").forEach(item=>item.classList.remove("active"));button.classList.add("active");setYear(button.dataset.year)}));
new Chart(document.getElementById("region-chart"),{type:"bar",data:{labels:DATA.regions.labels,datasets:[{data:DATA.regions.values,backgroundColor:["#caff3d","#69c6a4","#48a9ff","#9a78ff","#ff9a58"],borderRadius:7,borderSkipped:false}]},options:{responsive:true,maintainAspectRatio:false,scales:{x:{grid:{display:false},ticks:{color:"#aebcb7",font:{size:9}}},y:{beginAtZero:true,grid:{color:"rgba(255,255,255,.09)"},ticks:{...ticks,color:"#91a49e"}}},plugins:{tooltip:{callbacks:{label:c=>`${number(c.raw)} matrículas`}}}}});
new Chart(document.getElementById("courses-chart"),{type:"bar",data:{labels:DATA.courses.labels,datasets:[{data:DATA.courses.values,backgroundColor:DATA.courses.values.map((_,i)=>i===0?"#10211c":i<4?"#74a0f5":"#bdd0f2"),borderRadius:6,borderSkipped:false}]},options:{indexAxis:"y",responsive:true,maintainAspectRatio:false,scales:{x:{beginAtZero:true,grid,ticks},y:{grid:{display:false},ticks:{color:"#42514c",font:{size:10}}}},plugins:{tooltip:{callbacks:{label:c=>`${number(c.raw)} matrículas`}}}}});
document.getElementById("download-summary").addEventListener("click",()=>{const rows=[["indicador","2022","2023","2024"],["Matriculas TI",...DATA.flow.matriculas],["Ingressantes TI",...DATA.flow.ingressantes],["Concluintes TI",...DATA.flow.concluintes],["Matriculas TI EAD",...DATA.flow.years.map(y=>DATA.modalities[y].ead)],["Matriculas TI presencial",...DATA.flow.years.map(y=>DATA.modalities[y].presencial)],["Evasao TI EAD (%)",...DATA.flow.years.map(y=>DATA.modalities[y].evasaoEad)],["Evasao TI presencial (%)",...DATA.flow.years.map(y=>DATA.modalities[y].evasaoPres)]];const csv="\ufeff"+rows.map(row=>row.join(";")).join("\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const link=Object.assign(document.createElement("a"),{href:url,download:"resumo-formacao-ti-2022-2024.csv"});link.click();URL.revokeObjectURL(url)});
